[package]
name = "jated-cli"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]
description = ""
license = "MIT"
homepage = "https://github.com/unlink2/jated"
edition = "2021"

[[bin]]
name = "jated"
path = "src/main.rs"

[dependencies]
jated = {path = "../lib"}
