[package]
name = "sapp-cli"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]
description = ""
license = "MIT"
homepage = "https://github.com/unlink2/sapp"
edition = "2021"

[[bin]]
name = "sapp"
path = "src/main.rs"

[dependencies]
sapp = {path = "../lib"}
